name: Continuous integration 4.x
on: [push, pull_request]

jobs:
  build:
    name: Build (macOS)
    runs-on: "macos-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configuring Python
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Generate Headers
        run: |
          ./scripts/generate_headers.sh 4.0 || true

      - name: Compile Plugins
        run: |
          ./scripts/release_xcframework.sh 4.0
          ls -l bin/release

      - uses: actions/upload-artifact@v2
        with:
          name: plugins
          path: bin/release/*
          retention-days: 4
          if-no-files-found: error
